# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_create_tag(self) -> None:
        """Test case for create_tag

        Create tag
        """
        pass

    def test_delete_tag(self) -> None:
        """Test case for delete_tag

        Delete tag
        """
        pass

    def test_list_tags(self) -> None:
        """Test case for list_tags

        List tags
        """
        pass

    def test_update_tag(self) -> None:
        """Test case for update_tag

        Update tag
        """
        pass

    def test_update_tag_value(self) -> None:
        """Test case for update_tag_value

        Update tag value
        """
        pass


if __name__ == '__main__':
    unittest.main()
