# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.update_tag_value_request import UpdateTagValueRequest

class TestUpdateTagValueRequest(unittest.TestCase):
    """UpdateTagValueRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTagValueRequest:
        """Test UpdateTagValueRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTagValueRequest`
        """
        model = UpdateTagValueRequest()
        if include_optional:
            return UpdateTagValueRequest(
                value = ''
            )
        else:
            return UpdateTagValueRequest(
        )
        """

    def testUpdateTagValueRequest(self):
        """Test UpdateTagValueRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
