# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_authenticate_user(self) -> None:
        """Test case for authenticate_user

        Authenticate user
        """
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Create user
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete user
        """
        pass

    def test_destroy_user(self) -> None:
        """Test case for destroy_user

        Permanently delete user
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get user
        """
        pass

    def test_get_user_audits(self) -> None:
        """Test case for get_user_audits

        Get user audits
        """
        pass

    def test_get_user_transactions(self) -> None:
        """Test case for get_user_transactions

        Get user transactions
        """
        pass

    def test_list_deleted_users(self) -> None:
        """Test case for list_deleted_users

        List deleted users
        """
        pass

    def test_list_users(self) -> None:
        """Test case for list_users

        List users
        """
        pass

    def test_register_user(self) -> None:
        """Test case for register_user

        Register user
        """
        pass

    def test_remove_user_passkey(self) -> None:
        """Test case for remove_user_passkey

        Remove user passkey
        """
        pass

    def test_restore_user(self) -> None:
        """Test case for restore_user

        Restore deleted user
        """
        pass

    def test_set_user_tags(self) -> None:
        """Test case for set_user_tags

        Set user tags
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        Update user
        """
        pass


if __name__ == '__main__':
    unittest.main()
