# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.webhook_input import WebhookInput

class TestWebhookInput(unittest.TestCase):
    """WebhookInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookInput:
        """Test WebhookInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookInput`
        """
        model = WebhookInput()
        if include_optional:
            return WebhookInput(
                url = '',
                secret = 'my-webhook-secret',
                auth_group_id = '',
                events = api.models.webhook_events.Webhook_events(
                    verify = True, 
                    deny = True, )
            )
        else:
            return WebhookInput(
                url = '',
                events = api.models.webhook_events.Webhook_events(
                    verify = True, 
                    deny = True, ),
        )
        """

    def testWebhookInput(self):
        """Test WebhookInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
