# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.auth_group_member import AuthGroupMember

class TestAuthGroupMember(unittest.TestCase):
    """AuthGroupMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthGroupMember:
        """Test AuthGroupMember
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthGroupMember`
        """
        model = AuthGroupMember()
        if include_optional:
            return AuthGroupMember(
                id = '',
                email = '',
                first_name = '',
                last_name = ''
            )
        else:
            return AuthGroupMember(
        )
        """

    def testAuthGroupMember(self):
        """Test AuthGroupMember"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
