# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.settings_api import SettingsApi


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettingsApi()

    def tearDown(self) -> None:
        pass

    def test_get_settings(self) -> None:
        """Test case for get_settings

        Get organization settings
        """
        pass

    def test_update_settings(self) -> None:
        """Test case for update_settings

        Update organization settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
