# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_transaction(self) -> None:
        """Test case for cancel_transaction

        Cancel transaction
        """
        pass

    def test_check_transaction_status(self) -> None:
        """Test case for check_transaction_status

        Check transaction status
        """
        pass

    def test_get_transaction_history(self) -> None:
        """Test case for get_transaction_history

        Get transaction history
        """
        pass

    def test_list_transactions(self) -> None:
        """Test case for list_transactions

        List transactions
        """
        pass

    def test_set_transaction_tags(self) -> None:
        """Test case for set_transaction_tags

        Set transaction tags
        """
        pass


if __name__ == '__main__':
    unittest.main()
