# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.permissions_api import PermissionsApi


class TestPermissionsApi(unittest.TestCase):
    """PermissionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PermissionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_permission(self) -> None:
        """Test case for create_permission

        Create permission
        """
        pass

    def test_delete_permission(self) -> None:
        """Test case for delete_permission

        Delete permission
        """
        pass

    def test_list_permissions(self) -> None:
        """Test case for list_permissions

        List permissions
        """
        pass

    def test_rename_permission(self) -> None:
        """Test case for rename_permission

        Rename permission
        """
        pass


if __name__ == '__main__':
    unittest.main()
