# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.permission_group import PermissionGroup

class TestPermissionGroup(unittest.TestCase):
    """PermissionGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermissionGroup:
        """Test PermissionGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermissionGroup`
        """
        model = PermissionGroup()
        if include_optional:
            return PermissionGroup(
                id = '',
                name = '',
                permissions = [
                    ''
                    ]
            )
        else:
            return PermissionGroup(
                name = '',
        )
        """

    def testPermissionGroup(self):
        """Test PermissionGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
