# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.routing_rules_api import RoutingRulesApi


class TestRoutingRulesApi(unittest.TestCase):
    """RoutingRulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutingRulesApi()

    def tearDown(self) -> None:
        pass

    def test_authorize(self) -> None:
        """Test case for authorize

        Authorize a request
        """
        pass

    def test_create_routing_rule(self) -> None:
        """Test case for create_routing_rule

        Create routing rule
        """
        pass

    def test_delete_routing_rule(self) -> None:
        """Test case for delete_routing_rule

        Delete routing rule
        """
        pass

    def test_get_routing_rule(self) -> None:
        """Test case for get_routing_rule

        Get routing rules
        """
        pass

    def test_list_routing_rules(self) -> None:
        """Test case for list_routing_rules

        Get routing rules
        """
        pass

    def test_update_routing_rule(self) -> None:
        """Test case for update_routing_rule

        Update routing rule
        """
        pass


if __name__ == '__main__':
    unittest.main()
