# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.webhook import Webhook

class TestWebhook(unittest.TestCase):
    """Webhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Webhook:
        """Test Webhook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Webhook`
        """
        model = Webhook()
        if include_optional:
            return Webhook(
                id = '01234567-89ab-cdef-0123-456789abcdef',
                url = 'https://example.com/webhook',
                secret = 'my-webhook-secret',
                auth_group_id = '',
                events = api.models.webhook_events.Webhook_events(
                    verify = True, 
                    deny = True, ),
                created_at = '2024-01-15T10:30:00Z'
            )
        else:
            return Webhook(
                id = '01234567-89ab-cdef-0123-456789abcdef',
                url = 'https://example.com/webhook',
                events = api.models.webhook_events.Webhook_events(
                    verify = True, 
                    deny = True, ),
        )
        """

    def testWebhook(self):
        """Test Webhook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
