# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.authorize_reply_one_of1 import AuthorizeReplyOneOf1

class TestAuthorizeReplyOneOf1(unittest.TestCase):
    """AuthorizeReplyOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthorizeReplyOneOf1:
        """Test AuthorizeReplyOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorizeReplyOneOf1`
        """
        model = AuthorizeReplyOneOf1()
        if include_optional:
            return AuthorizeReplyOneOf1(
                approval_id = ''
            )
        else:
            return AuthorizeReplyOneOf1(
        )
        """

    def testAuthorizeReplyOneOf1(self):
        """Test AuthorizeReplyOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
