# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.audits_api import AuditsApi


class TestAuditsApi(unittest.TestCase):
    """AuditsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuditsApi()

    def tearDown(self) -> None:
        pass

    def test_list_audits(self) -> None:
        """Test case for list_audits

        List audits
        """
        pass


if __name__ == '__main__':
    unittest.main()
