# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.tag_list_reply import TagListReply

class TestTagListReply(unittest.TestCase):
    """TagListReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagListReply:
        """Test TagListReply
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagListReply`
        """
        model = TagListReply()
        if include_optional:
            return TagListReply(
                tags = [
                    api.models.tag.Tag(
                        id = '01234567-89ab-cdef-0123-456789abcdef', 
                        name = 'priority', 
                        description = 'Indicates the priority level', 
                        enabled = True, 
                        values = [
                            'high'
                            ], )
                    ]
            )
        else:
            return TagListReply(
        )
        """

    def testTagListReply(self):
        """Test TagListReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
