# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.approval_groups_api import ApprovalGroupsApi


class TestApprovalGroupsApi(unittest.TestCase):
    """ApprovalGroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApprovalGroupsApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_to_auth_group(self) -> None:
        """Test case for add_user_to_auth_group

        Add user to approval group
        """
        pass

    def test_create_auth_group(self) -> None:
        """Test case for create_auth_group

        Create approval group
        """
        pass

    def test_delete_auth_group(self) -> None:
        """Test case for delete_auth_group

        Delete approval group
        """
        pass

    def test_get_auth_group(self) -> None:
        """Test case for get_auth_group

        Get approval group
        """
        pass

    def test_list_auth_groups(self) -> None:
        """Test case for list_auth_groups

        List approval groups
        """
        pass

    def test_remove_user_from_auth_group(self) -> None:
        """Test case for remove_user_from_auth_group

        Remove user from approval group
        """
        pass

    def test_set_auth_group_tags(self) -> None:
        """Test case for set_auth_group_tags

        Set approval group tags
        """
        pass

    def test_update_auth_group(self) -> None:
        """Test case for update_auth_group

        Update approval group
        """
        pass


if __name__ == '__main__':
    unittest.main()
