# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.auth_group import AuthGroup

class TestAuthGroup(unittest.TestCase):
    """AuthGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthGroup:
        """Test AuthGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthGroup`
        """
        model = AuthGroup()
        if include_optional:
            return AuthGroup(
                id = '',
                name = '',
                threshold = '1',
                description = '',
                users = [
                    api.models.auth_group_member.AuthGroupMember(
                        id = '', 
                        email = '', 
                        first_name = '', 
                        last_name = '', )
                    ]
            )
        else:
            return AuthGroup(
                name = '',
                threshold = '1',
        )
        """

    def testAuthGroup(self):
        """Test AuthGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
