# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.approvals_api import ApprovalsApi


class TestApprovalsApi(unittest.TestCase):
    """ApprovalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApprovalsApi()

    def tearDown(self) -> None:
        pass

    def test_authorize(self) -> None:
        """Test case for authorize

        Authorize a request
        """
        pass

    def test_get_approval(self) -> None:
        """Test case for get_approval

        Get an approval request
        """
        pass


if __name__ == '__main__':
    unittest.main()
