# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.set_permission_group_permissions_request import SetPermissionGroupPermissionsRequest

class TestSetPermissionGroupPermissionsRequest(unittest.TestCase):
    """SetPermissionGroupPermissionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetPermissionGroupPermissionsRequest:
        """Test SetPermissionGroupPermissionsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetPermissionGroupPermissionsRequest`
        """
        model = SetPermissionGroupPermissionsRequest()
        if include_optional:
            return SetPermissionGroupPermissionsRequest(
                permissions = [
                    ''
                    ]
            )
        else:
            return SetPermissionGroupPermissionsRequest(
        )
        """

    def testSetPermissionGroupPermissionsRequest(self):
        """Test SetPermissionGroupPermissionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
