# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.companies_api import CompaniesApi


class TestCompaniesApi(unittest.TestCase):
    """CompaniesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompaniesApi()

    def tearDown(self) -> None:
        pass

    def test_create_company(self) -> None:
        """Test case for create_company

        Create company
        """
        pass

    def test_delete_company(self) -> None:
        """Test case for delete_company

        Delete company
        """
        pass

    def test_list_companies(self) -> None:
        """Test case for list_companies

        List companies
        """
        pass

    def test_update_company(self) -> None:
        """Test case for update_company

        Update company
        """
        pass


if __name__ == '__main__':
    unittest.main()
