# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.routing_rule import RoutingRule

class TestRoutingRule(unittest.TestCase):
    """RoutingRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoutingRule:
        """Test RoutingRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoutingRule`
        """
        model = RoutingRule()
        if include_optional:
            return RoutingRule(
                id = '',
                tag_name = '',
                tag_value = '',
                description = '',
                target_type = 'approval_group',
                target_id = '',
                target_email = '',
                target_name = ''
            )
        else:
            return RoutingRule(
                tag_name = '',
                tag_value = '',
                target_type = 'approval_group',
                target_id = '',
        )
        """

    def testRoutingRule(self):
        """Test RoutingRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
