# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook(self) -> None:
        """Test case for create_webhook

        Create a new webhook
        """
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Delete a webhook
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        List all webhooks
        """
        pass

    def test_update_webhook(self) -> None:
        """Test case for update_webhook

        Update a webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
