# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.api.permission_groups_api import PermissionGroupsApi


class TestPermissionGroupsApi(unittest.TestCase):
    """PermissionGroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PermissionGroupsApi()

    def tearDown(self) -> None:
        pass

    def test_create_permission_group(self) -> None:
        """Test case for create_permission_group

        Create permission group
        """
        pass

    def test_delete_permission_group(self) -> None:
        """Test case for delete_permission_group

        Delete permission group
        """
        pass

    def test_list_permission_groups(self) -> None:
        """Test case for list_permission_groups

        List permission groups
        """
        pass

    def test_rename_permission_group(self) -> None:
        """Test case for rename_permission_group

        Rename permission group
        """
        pass

    def test_set_permission_group_permissions(self) -> None:
        """Test case for set_permission_group_permissions

        Set permission group permissions
        """
        pass


if __name__ == '__main__':
    unittest.main()
