# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.settings import Settings

class TestSettings(unittest.TestCase):
    """Settings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Settings:
        """Test Settings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Settings`
        """
        model = Settings()
        if include_optional:
            return Settings(
                subdomain = '01',
                name = '',
                open_id = api.models.open_id.OpenID(
                    issuer = '', 
                    client_id = '', 
                    client_secret = '', ),
                scim_secret = '01234567891011121314151617181920212223',
                email_template = '',
                sms_template = '',
                connect_wise = api.models.connect_wise.ConnectWise(
                    enabled = True, 
                    server_url = '', 
                    company_id = '', 
                    public_key = '', 
                    private_key = '', 
                    api_version = '', )
            )
        else:
            return Settings(
        )
        """

    def testSettings(self):
        """Test Settings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
