# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.authorize_request import AuthorizeRequest

class TestAuthorizeRequest(unittest.TestCase):
    """AuthorizeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthorizeRequest:
        """Test AuthorizeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorizeRequest`
        """
        model = AuthorizeRequest()
        if include_optional:
            return AuthorizeRequest(
                message = '0',
                tag = {
                    'key' : ''
                    },
                context = '',
                payload = { }
            )
        else:
            return AuthorizeRequest(
                message = '0',
                tag = {
                    'key' : ''
                    },
        )
        """

    def testAuthorizeRequest(self):
        """Test AuthorizeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
