# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.create_tag_request import CreateTagRequest

class TestCreateTagRequest(unittest.TestCase):
    """CreateTagRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTagRequest:
        """Test CreateTagRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTagRequest`
        """
        model = CreateTagRequest()
        if include_optional:
            return CreateTagRequest(
                name = '',
                description = '',
                enabled = True,
                values = [
                    ''
                    ]
            )
        else:
            return CreateTagRequest(
        )
        """

    def testCreateTagRequest(self):
        """Test CreateTagRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
