# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.paginated_audits import PaginatedAudits

class TestPaginatedAudits(unittest.TestCase):
    """PaginatedAudits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedAudits:
        """Test PaginatedAudits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedAudits`
        """
        model = PaginatedAudits()
        if include_optional:
            return PaginatedAudits(
                rows = [
                    api.models.audit.Audit(
                        subject = '', 
                        name = '', 
                        type = '', 
                        actor = '', 
                        action = '', 
                        extras = {
                            'key' : ''
                            }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 56
            )
        else:
            return PaginatedAudits(
        )
        """

    def testPaginatedAudits(self):
        """Test PaginatedAudits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
