# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.models.paginated_transactions import PaginatedTransactions

class TestPaginatedTransactions(unittest.TestCase):
    """PaginatedTransactions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedTransactions:
        """Test PaginatedTransactions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedTransactions`
        """
        model = PaginatedTransactions()
        if include_optional:
            return PaginatedTransactions(
                rows = [
                    api.models.transaction.Transaction(
                        id = '', 
                        subject = '', 
                        subject_name = '', 
                        state = 'pending', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        requestor = '', 
                        context = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        message = '', 
                        user_message = '', )
                    ],
                total = 56
            )
        else:
            return PaginatedTransactions(
        )
        """

    def testPaginatedTransactions(self):
        """Test PaginatedTransactions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
