# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class RoutingRule(BaseModel):
    """
    RoutingRule
    """ # noqa: E501
    id: Optional[UUID] = None
    tag_name: StrictStr = Field(description="Name of tag associated with the routing rule", alias="tagName")
    tag_value: StrictStr = Field(description="Tag value that must match for this rule to fire", alias="tagValue")
    description: Optional[StrictStr] = None
    target_type: StrictStr = Field(description="The type of target for the routing rule", alias="targetType")
    target_id: UUID = Field(description="The ID of the target (approval group or user)", alias="targetId")
    target_email: Optional[StrictStr] = Field(default=None, description="The email of the target", alias="targetEmail")
    target_name: Optional[StrictStr] = Field(default=None, description="The name of the target", alias="targetName")
    __properties: ClassVar[List[str]] = ["id", "tagName", "tagValue", "description", "targetType", "targetId", "targetEmail", "targetName"]

    @field_validator('target_type')
    def target_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['approval_group', 'user']):
            raise ValueError("must be one of enum values ('approval_group', 'user')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RoutingRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RoutingRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in RoutingRule) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "tagName": obj.get("tagName"),
            "tagValue": obj.get("tagValue"),
            "description": obj.get("description"),
            "targetType": obj.get("targetType"),
            "targetId": obj.get("targetId"),
            "targetEmail": obj.get("targetEmail"),
            "targetName": obj.get("targetName")
        })
        return _obj


