# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class Audit(BaseModel):
    """
    Audit
    """ # noqa: E501
    subject: Optional[UUID] = Field(default=None, description="Subject identifier")
    name: Optional[StrictStr] = Field(default=None, description="Subject name")
    type: Optional[StrictStr] = Field(default=None, description="Subject type")
    actor: Optional[StrictStr] = Field(default=None, description="Actor performing the action")
    action: Optional[StrictStr] = Field(default=None, description="Action performed")
    extras: Optional[Dict[str, StrictStr]] = Field(default=None, description="Additional audit information")
    created_at: Optional[datetime] = Field(default=None, description="Audit entry creation timestamp")
    __properties: ClassVar[List[str]] = ["subject", "name", "type", "actor", "action", "extras", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Audit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Audit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in Audit) in the input: " + _key)

        _obj = cls.model_validate({
            "subject": obj.get("subject"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "actor": obj.get("actor"),
            "action": obj.get("action"),
            "extras": obj.get("extras"),
            "created_at": obj.get("created_at")
        })
        return _obj


