# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from api.models.auth_group_member import AuthGroupMember
from typing import Optional, Set
from typing_extensions import Self

class AuthGroup(BaseModel):
    """
    AuthGroup
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="The unique identifier of the approval group")
    name: Annotated[str, Field(strict=True, max_length=128)] = Field(description="The name of the approval group")
    threshold: StrictStr = Field(description="The threshold for the approval group")
    description: Optional[StrictStr] = None
    users: Optional[List[AuthGroupMember]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "threshold", "description", "users"]

    @field_validator('threshold')
    def threshold_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['1', '2', '3', '4', '5', 'any', 'all']):
            raise ValueError("must be one of enum values ('1', '2', '3', '4', '5', 'any', 'all')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item_users in self.users:
                if _item_users:
                    _items.append(_item_users.to_dict())
            _dict['users'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in AuthGroup) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "threshold": obj.get("threshold"),
            "description": obj.get("description"),
            "users": [AuthGroupMember.from_dict(_item) for _item in obj["users"]] if obj.get("users") is not None else None
        })
        return _obj


