# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Query(BaseModel):
    """
    Query
    """ # noqa: E501
    page: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Page number")
    per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=None, description="Items per page", alias="perPage")
    q: Optional[StrictStr] = Field(default=None, description="Search query")
    permission: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Filter by permission")
    sort_by: Optional[StrictStr] = Field(default=None, description="Sort field", alias="sortBy")
    sort_dir: Optional[StrictStr] = Field(default=None, description="Sort direction", alias="sortDir")
    __properties: ClassVar[List[str]] = ["page", "perPage", "q", "permission", "sortBy", "sortDir"]

    @field_validator('sort_dir')
    def sort_dir_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['asc', 'desc']):
            raise ValueError("must be one of enum values ('asc', 'desc')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Query from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Query from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in Query) in the input: " + _key)

        _obj = cls.model_validate({
            "page": obj.get("page"),
            "perPage": obj.get("perPage"),
            "q": obj.get("q"),
            "permission": obj.get("permission"),
            "sortBy": obj.get("sortBy"),
            "sortDir": obj.get("sortDir")
        })
        return _obj


