# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from api.models.connect_wise import ConnectWise
from api.models.open_id import OpenID
from typing import Optional, Set
from typing_extensions import Self

class Settings(BaseModel):
    """
    Settings
    """ # noqa: E501
    subdomain: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=64)]] = Field(default=None, description="Organization subdomain")
    name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Organization name")
    open_id: Optional[OpenID] = Field(default=None, alias="openID")
    scim_secret: Optional[Annotated[str, Field(min_length=24, strict=True, max_length=256)]] = Field(default=None, description="SCIM API secret", alias="scimSecret")
    email_template: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = Field(default=None, description="Email notification template", alias="emailTemplate")
    sms_template: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="SMS notification template", alias="smsTemplate")
    connect_wise: Optional[ConnectWise] = Field(default=None, alias="connectWise")
    __properties: ClassVar[List[str]] = ["subdomain", "name", "openID", "scimSecret", "emailTemplate", "smsTemplate", "connectWise"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Settings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of open_id
        if self.open_id:
            _dict['openID'] = self.open_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of connect_wise
        if self.connect_wise:
            _dict['connectWise'] = self.connect_wise.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Settings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in Settings) in the input: " + _key)

        _obj = cls.model_validate({
            "subdomain": obj.get("subdomain"),
            "name": obj.get("name"),
            "openID": OpenID.from_dict(obj["openID"]) if obj.get("openID") is not None else None,
            "scimSecret": obj.get("scimSecret"),
            "emailTemplate": obj.get("emailTemplate"),
            "smsTemplate": obj.get("smsTemplate"),
            "connectWise": ConnectWise.from_dict(obj["connectWise"]) if obj.get("connectWise") is not None else None
        })
        return _obj


