# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from api.models.company import Company
from typing import Optional, Set
from typing_extensions import Self

class User(BaseModel):
    """
    User
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Unique user identifier")
    role: Optional[StrictStr] = Field(default=None, description="User role")
    username: Optional[StrictStr] = Field(default=None, description="Display username")
    first_name: Annotated[str, Field(min_length=2, strict=True, max_length=50)] = Field(description="User first name", alias="firstName")
    last_name: Annotated[str, Field(min_length=2, strict=True, max_length=50)] = Field(description="User last name", alias="lastName")
    email: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="User email address")
    phone: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, description="User phone number")
    company: Optional[Company] = None
    permissions: Optional[List[Annotated[str, Field(strict=True, max_length=64)]]] = Field(default=None, description="User direct permissions")
    group_permissions: Optional[List[Annotated[str, Field(strict=True, max_length=64)]]] = Field(default=None, description="Permissions from groups", alias="groupPermissions")
    permission_groups: Optional[List[UUID]] = Field(default=None, description="Permission group IDs", alias="permissionGroups")
    messaging_preference: Optional[StrictStr] = Field(default=None, description="User messaging preference", alias="messagingPreference")
    has_passkeys: Optional[StrictBool] = Field(default=None, description="Whether user has passkeys configured", alias="hasPasskeys")
    created_at: Optional[datetime] = Field(default=None, description="User creation timestamp", alias="createdAt")
    last_authenticated: Optional[datetime] = Field(default=None, description="Last authentication timestamp", alias="lastAuthenticated")
    __properties: ClassVar[List[str]] = ["id", "role", "username", "firstName", "lastName", "email", "phone", "company", "permissions", "groupPermissions", "permissionGroups", "messagingPreference", "hasPasskeys", "createdAt", "lastAuthenticated"]

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['admin', 'user', 'super_admin']):
            raise ValueError("must be one of enum values ('admin', 'user', 'super_admin')")
        return value

    @field_validator('messaging_preference')
    def messaging_preference_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['email', 'sms', 'both']):
            raise ValueError("must be one of enum values ('email', 'sms', 'both')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "username",
            "has_passkeys",
            "created_at",
            "last_authenticated",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['company'] = self.company.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in User) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "role": obj.get("role"),
            "username": obj.get("username"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "company": Company.from_dict(obj["company"]) if obj.get("company") is not None else None,
            "permissions": obj.get("permissions"),
            "groupPermissions": obj.get("groupPermissions"),
            "permissionGroups": obj.get("permissionGroups"),
            "messagingPreference": obj.get("messagingPreference"),
            "hasPasskeys": obj.get("hasPasskeys"),
            "createdAt": obj.get("createdAt"),
            "lastAuthenticated": obj.get("lastAuthenticated")
        })
        return _obj


