# coding: utf-8

"""
    SendAuth API

    Authentication and identity management API for SendAuth platform

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from api.models.webhook_events import WebhookEvents
from typing import Optional, Set
from typing_extensions import Self

class Webhook(BaseModel):
    """
    A webhook configuration object
    """ # noqa: E501
    id: UUID = Field(description="The unique identifier of the webhook")
    url: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="The URL where webhook events will be sent")
    secret: Optional[StrictStr] = Field(default=None, description="Optional secret used to sign webhook payloads (HMAC-SHA256)")
    auth_group_id: Optional[UUID] = Field(default=None, description="Optional approval group ID to associate with the webhook", alias="authGroupID")
    events: WebhookEvents
    created_at: Optional[datetime] = Field(default=None, description="When the webhook was created", alias="createdAt")
    __properties: ClassVar[List[str]] = ["id", "url", "secret", "authGroupID", "events", "createdAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Webhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of events
        if self.events:
            _dict['events'] = self.events.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Webhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in Webhook) in the input: " + _key)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "url": obj.get("url"),
            "secret": obj.get("secret"),
            "authGroupID": obj.get("authGroupID"),
            "events": WebhookEvents.from_dict(obj["events"]) if obj.get("events") is not None else None,
            "createdAt": obj.get("createdAt")
        })
        return _obj


